name: investor_go_app
services:
  postgresdb:
    container_name: investor-postgresdb
    image: postgres
    restart: always
    ports:
      - ${PG_PORT_DOCKER}:5432
    environment:
      - POSTGRES_USER=${PG_USERNAME}
      - POSTGRES_DB=${PG_DB_NAME}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
    volumes:
      - ./docker-volumes/postgres:/var/lib/postgresql/data
    networks:
      - investor_network
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "-h",
          "postgresdb",
          "-p",
          "5432",
          "-U",
          "${PG_DB_NAME}",
        ]
      interval: 10s
      retries: 10

  redis:
    container_name: investor-redis
    image: redis:6.2-alpine
    restart: always
    ports:
      - ${DOCKER_REDIS_PORT}:6379
    command: redis-server --save 60 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    volumes:
      - ./docker-volumes/redis/data:/data
      # - ./docker-volumes/redis/redis.conf:/usr/local/etc/redis/redis.conf

  backend:
    container_name: investor-go-backend
    build:
      context: ./go-api
      dockerfile: Dockerfile
    depends_on:
      postgresdb:
        condition: service_healthy
    ports:
      - ${GO_API_PORT_DOCKER}:${GO_API_PORT}
    networks:
      - investor_network

  frontend:
    container_name: investor-next-client
    build:
      context: ./next-client
      dockerfile: Dockerfile
    ports:
      - ${DOCKER_NEXT_CLIENT_PORT}:${NEXT_CLIENT_PORT}
    networks:
      - investor_network

networks:
  investor_network:
    name: investor_network
