name: investor_go_app
services:
  postgresdb:
    container_name: investor-postgresdb
    image: postgres
    restart: always
    ports:
      - ${DOCKER_PG_PORT}:5432
    environment:
      - POSTGRES_USER=${PG_USERNAME}
      - POSTGRES_DB=${PG_DB_NAME}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
    volumes:
      - ./docker-volumes/postgres:/var/lib/postgresql/data
    networks:
      - investor_network
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "-h",
          "postgresdb",
          "-p",
          "5432",
          "-U",
          "${PG_DB_NAME}",
        ]
      interval: 10s
      retries: 10

  prometheus:
    container_name: investor-prometheus
    image: prom/prometheus:latest
    restart: always
    ports:
      - ${DOCKER_PROMETHEUS_PORT}:9090
    volumes:
      - ./docker-volumes/prometheus:/etc/prometheus

  redis:
    container_name: investor-redis
    image: redis:6.2-alpine
    restart: always
    ports:
      - ${DOCKER_REDIS_PORT}:6379
    command: redis-server --save 60 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    volumes:
      - ./docker-volumes/redis/data:/data
      # - ./docker-volumes/redis/redis.conf:/usr/local/etc/redis/redis.conf

  backend:
    container_name: investor-go-backend
    build:
      context: ./go-api
      dockerfile: Dockerfile
    depends_on:
      postgresdb:
        condition: service_healthy
    environment:
      - GO_API_PORT=${GO_API_PORT}
      - DOCKER_GO_API_PORT=${DOCKER_GO_API_PORT}
    ports:
      - ${DOCKER_GO_API_PORT}:${GO_API_PORT}
    networks:
      - investor_network

  frontend:
    container_name: investor-next-client
    build:
      context: ./next-client
      dockerfile: Dockerfile
    ports:
      - ${DOCKER_NEXT_CLIENT_PORT}:${NEXT_CLIENT_PORT}
    networks:
      - investor_network

  grafana:
    container_name: investor-grafana
    image: grafana/grafana
    restart: unless-stopped
    ports:
      - ${DOCKER_GRAFANA_PORT}:3000
    volumes:
      - ./docker-volumes/grafana:/var/lib/grafana

networks:
  investor_network:
    name: investor_network
