version: "3.9"

name: investor_go_app
services:
  postgresdb:
    container_name: investor-postgresdb
    image: postgres
    restart: always
    ports:
      - ${DOCKER_PG_PORT}:5432
    environment:
      - POSTGRES_USER=${PG_USERNAME}
      - POSTGRES_DB=${PG_DB_NAME}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
    volumes:
      - ./docker-volumes/postgres:/var/lib/postgresql/data
    networks:
      - investor_network
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "-h",
          "postgresdb",
          "-p",
          "5432",
          "-U",
          "${PG_DB_NAME}",
        ]
      interval: 10s
      retries: 10

  backend:
    container_name: investor-go-backend
    logging:
      # Указываем, какой драйвер использовать
      driver: loki
      options:
        # Адрес Loki, куда складывать логи
        # Обратите внимание, что здесь используется не имя сервиса loki, а локальный хост, на который проброшен порт Loki,
        # это сделано потому, что логи будет писать docker engine, котрый расположен на хостовой машине,
        # и он не знает имени хоста контейнера Loki, которое ему присвоил compose во внутренней сети проекта.
        loki-url: "http://localhost:4100/loki/api/v1/push"
        loki-batch-size: "100"
        loki-retries: 2
        loki-max-backoff: 1000ms
        loki-timeout: 1s
    build:
      context: ./go-api
      dockerfile: Dockerfile
    depends_on:
      postgresdb:
        condition: service_healthy
      loki:
        condition: service_started
      prometheus:
        condition: service_started
    environment:
      - GO_API_PORT=${GO_API_PORT}
      - DOCKER_GO_API_PORT=${DOCKER_GO_API_PORT}
    ports:
      - ${DOCKER_GO_API_PORT}:${GO_API_PORT}
    networks:
      - investor_network

  frontend:
    container_name: investor-next-client
    build:
      context: ./next-client
      dockerfile: Dockerfile
    ports:
      - ${DOCKER_NEXT_CLIENT_PORT}:${NEXT_CLIENT_PORT}
    networks:
      - investor_network

  grafana:
    container_name: investor-grafana
    image: grafana/grafana
    restart: unless-stopped
    ports:
      - ${DOCKER_GRAFANA_PORT}:3000
    volumes:
      - ./docker-volumes/grafana:/var/lib/grafana

  loki:
    container_name: investor-loki
    hostname: loki
    image: grafana/loki:latest
    ports:
      - ${DOCKER_LOKI_PORT}:3100
    volumes:
      - ./docker-volumes/loki:/etc/loki
    command: -config.file=/etc/loki/retention-config.yaml

  prometheus:
    container_name: investor-prometheus
    image: prom/prometheus:latest
    restart: always
    ports:
      - ${DOCKER_PROMETHEUS_PORT}:9090
    volumes:
      - ./docker-volumes/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  promtail:
    container_name: investor-promtail
    image: grafana/promtail:latest
    ports:
      - 4080:9080
    volumes:
      - ./docker-volumes/promtail:/etc/promtail

  redis:
    container_name: investor-redis
    image: redis:6.2-alpine
    restart: always
    ports:
      - ${DOCKER_REDIS_PORT}:6379
    command: redis-server --save 60 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    volumes:
      - ./docker-volumes/redis/data:/data

networks:
  investor_network:
    name: investor_network
