// Package iss provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package iss

// MoexAPICurrentPricesResponse defines model for MoexAPICurrentPricesResponse.
type MoexAPICurrentPricesResponse struct {
	Securities *struct {
		Data *[][]interface{} `json:"data,omitempty"`
	} `json:"securities,omitempty"`
}

// MoexAPISecurityInfoResponse defines model for MoexAPISecurityInfoResponse.
type MoexAPISecurityInfoResponse struct {
	Boards *struct {
		Data *[][]string `json:"data,omitempty"`
	} `json:"boards,omitempty"`
	Description *struct {
		Data *[][]string `json:"data,omitempty"`
	} `json:"description,omitempty"`
}

// GetEnginesStockMarketsMarketSecuritiesJsonParams defines parameters for GetEnginesStockMarketsMarketSecuritiesJson.
type GetEnginesStockMarketsMarketSecuritiesJsonParams struct {
	// IssMeta нужно ставить "off", чтобы убрать лишнюю инфу из запросов
	IssMeta *string `form:"iss.meta,omitempty" json:"iss.meta,omitempty"`

	// DescriptionColumns список полей, которые нужны в ответе. Иначе прилетит много лишнего
	DescriptionColumns string `form:"description.columns" json:"description.columns"`

	// BoardsColumns список полей, которые нужны в ответе. Иначе прилетит много лишнего
	BoardsColumns string `form:"boards.columns" json:"boards.columns"`
}
