openapi: 3.0.3
info:
  title: Investor API
  description: REST API для приложения "Инвестор"
  version: 1.0.0
paths:
  /deal:
    post:
      summary: Создание новой сделки
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateDealRequest'
      responses:
        '201':
          description: сделка добавлена
        '400':
          description: неверный формат JSON
        '422':
          description: неправильно заполнены поля
        '500':
          description: другие ошибки, должен быть текст в ответе
  /deal/{id}:
    delete:
      summary: Удаление сделки по id
      parameters:
        - name: id
          in: path
          schema:
            type: integer
          required: true
          decription: Айдишник сделки
      responses:
        '200':
          description: Сделка удалена
        '400':
          description: Неправильный формат айди в параметрах
        '401':
          description: Такой сделки нет, либо не пренадлежит текущему юзеру
        '500':
          description: Другие ошибки, должен быть текст в ответе
  /expert:
    get:
      summary: Список экспертов, созданных текущим юзером
      responses:
        '200':
          description: удачный запрос
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExpertListResponse'
        '400':
          description: неверный формат JSON
        '422':
          description: неправильно заполнены поля
        '500':
          description: другие ошибки, должен быть текст в ответе
    post:
      summary: Создание нового эксперта
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateExpertRequest'
      responses:
        '201':
          description: эксперт создан
        '400':
          description: неверный формат JSON
        '422':
          description: неправильно заполнены поля
        '500':
          description: другие ошибки, должен быть текст в ответе
  /login:
    post:
      summary: Регистрация нового юзера
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: успешно залогинен
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'
        '400':
          description: неверный формат JSON
        '401':
          description: Ановтарайзед
  /moex-bond/{secid}:
    get:
      summary: Получение информации по облигации, торгуемой на мск бирже
      parameters:
        - name: secid
          in: path
          schema:
            type: string
          required: true
          decription: secid облигации
      responses:
        '200':
          description: удачный запрос
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MoexBondResponse'
        '400':
          description: Неправильный формат айди в параметрах
        '401':
          description: Такого портфолио нет, либо не пренадлежит текущему юзеру
        '500':
          description: Другие ошибки, должен быть текст в ответе
  /moex-share/{secid}:
    get:
      summary: Получение информации по акции, торгуемой на мск бирже
      parameters:
        - name: secid
          in: path
          schema:
            type: string
          required: true
          decription: secid акции
      responses:
        '200':
          description: удачный запрос
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MoexShareResponse'
        '400':
          description: Неправильный формат айди в параметрах
        '401':
          description: Такого портфолио нет, либо не пренадлежит текущему юзеру
        '500':
          description: Другие ошибки, должен быть текст в ответе
  /opinion:
    post:
      summary: Создание нового мнения
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateOpinionRequest'
      responses:
        '201':
          description: мнение успещно создано
        '400':
          description: неверный формат JSON
        '422':
          description: неправильно заполнены поля
        '500':
          description: другие ошибки, должен быть текст в ответе
  /opinion/list:
    get:
      summary: Получение списка мнений
      parameters:
        - name: expertId
          in: query
          required: false
          schema:
            type: integer
          description: id эксперта
        - name: securityId
          in: query
          required: false
          schema:
            type: integer
          description: id бумаги
        - name: exchange
          in: query
          required: false
          schema:
            type: string
          description: Биржа
        - name: securityType
          in: query
          required: false
          schema:
            type: string
          description: тип бумаги SHARE BOND ...
      responses:
        '200':
          description: список отправлен
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/OpinionResponse'
        '400':
          description: неверный запрос
        '500':
          description: другие ошибки, должен быть текст в ответе
  /portfolio:
    get:
      summary: Список портфолио юзера
      responses:
        '200':
          description: удачный запрос
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PortfolioListResponse'
        '400':
          description: неверный формат JSON
        '422':
          description: неправильно заполнены поля
        '500':
          description: другие ошибки, должен быть текст в ответе
    post:
      summary: Создание нового портфолио
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreatePortfolioRequest'
      responses:
        '201':
          description: портфолио создан
        '400':
          description: неверный формат JSON
        '422':
          description: неправильно заполнены поля
        '500':
          description: другие ошибки, должен быть текст в ответе
    put:
      summary: Редактирование портфолио
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdatePortfolioRequest'
      responses:
        '200':
          description: портфолио отредактирован
        '400':
          description: неверный формат JSON
        '404':
          description: такого портфолио нет или он не пренадлежит юзеру
        '500':
          description: другие ошибки, должен быть текст в ответе
  /portfolio/{id}:
    get:
      summary: Получение портфолио по id
      parameters:
        - name: id
          in: path
          schema:
            type: integer
          required: true
          decription: Айдишник портфолио
      responses:
        '200':
          description: удачный запрос
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FullPortfolioResponse'
        '400':
          description: Неправильный формат айди в параметрах
        '401':
          description: Такого портфолио нет, либо не пренадлежит текущему юзеру
        '500':
          description: Другие ошибки, должен быть текст в ответе
    delete:
      summary: Удаление портфолио по id
      parameters:
        - name: id
          in: path
          schema:
            type: integer
          required: true
          decription: Айдишник портфолио
      responses:
        '200':
          description: Портфолио удален
        '400':
          description: Неправильный формат айди в параметрах
        '401':
          description: Такого портфолио нет, либо не пренадлежит текущему юзеру
        '500':
          description: Другие ошибки, должен быть текст в ответе
  /register:
    post:
      summary: Регистрация нового юзера
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterUserRequest'
      responses:
        '201':
          description: юзер удачно создан
        '400':
          description: неверный формат JSON
        '422':
          description: неправильно заполнены поля
        '500':
          description: другие ошибки, должен быть текст в ответе
  /transaction:
    post:
      summary: Транзакция успешно создана
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateTransactionRequest'
      responses:
        '201':
          description: транзакция создана
        '400':
          description: неверный формат JSON
        '422':
          description: неправильно заполнены поля
        '500':
          description: другие ошибки, должен быть текст в ответе
  /transaction/{id}:
    delete:
      summary: Удаление транзакции по id
      parameters:
        - name: id
          in: path
          schema:
            type: integer
          required: true
          decription: Айдишник транзакции
      responses:
        '200':
          description: Транзакция удалена
        '400':
          description: Неправильный формат айди в параметрах
        '401':
          description: Такой сделки нет, либо не пренадлежит текущему юзеру
        '500':
          description: Другие ошибки, должен быть текст в ответе
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
security:
  - BearerAuth: []
components:
  schemas:
    Exchange:
      type: string
      enum:
        - MOEX
      x-oapi-codegen-extra-tags:
        validate: required,is-exchange
    SecurityType:
      type: string
      enum:
        - BOND
        - CURRENCY
        - FUTURES
        - INDEX
        - PIF
        - SHARE
      x-oapi-codegen-extra-tags:
        validate: required,securityType
    DealType:
      type: string
      enum:
        - BUY
        - SELL
    CreateDealRequest:
      type: object
      required:
        - amount
        - comission
        - date
        - exchange
        - portfolioId
        - price
        - secId
        - securityType
        - type
        - ticker
      properties:
        amount:
          type: integer
        comission:
          type: number
          format: double
        date:
          type: string
          format: date-time
        exchange:
          $ref: '#/components/schemas/Exchange'
        portfolioId:
          type: integer
        price:
          type: number
          format: double
        secId:
          type: string
        securityType:
          $ref: '#/components/schemas/SecurityType'
        type:
          $ref: '#/components/schemas/DealType'
    ExpertResponse:
      type: object
      required:
        - id
        - name
      properties:
        avatarUrl:
          type: string
        id:
          type: integer
        name:
          type: string
        userId:
          type: integer
    ExpertListResponse:
      type: array
      items:
        $ref: '#/components/schemas/ExpertResponse'
    CreateExpertRequest:
      type: object
      required:
        - name
      properties:
        avatarUrl:
          type: string
        name:
          type: string
    LoginRequest:
      type: object
      required:
        - email
        - password
      properties:
        email:
          type: string
        password:
          type: string
    LoginResponse:
      type: object
      properties:
        token:
          type: string
    ISSMoexBoard:
      type: string
      enum:
        - TQBR
        - CETS
    ISSMoexEngine:
      type: string
      enum:
        - stock
        - currency
    ISSMoexMarket:
      type: string
      enum:
        - bonds
        - shares
    MoexSecurityResponse:
      type: object
      required:
        - board
        - engine
        - id
        - lotSize
        - market
        - name
        - secid
        - shortName
      properties:
        board:
          $ref: '#/components/schemas/ISSMoexBoard'
        engine:
          $ref: '#/components/schemas/ISSMoexEngine'
        id:
          type: integer
        lotSize:
          type: integer
        market:
          $ref: '#/components/schemas/ISSMoexMarket'
        name:
          type: string
        secid:
          type: string
        shortName:
          type: string
    MoexBondResponse:
      allOf:
        - $ref: '#/components/schemas/MoexSecurityResponse'
        - type: object
          required:
            - couponPercent
            - couponValue
            - couponFrequency
            - issueDate
            - faceValue
            - matDate
          properties:
            couponPercent:
              type: number
              format: double
              description: купон в процентах
            couponValue:
              type: number
              format: double
              description: купон в деньгах
            couponFrequency:
              type: integer
              description: частота выплаты купонов в год
            issueDate:
              type: string
              format: date
            faceValue:
              type: integer
              description: номинальная стоимость
            matDate:
              type: string
              format: date
    MoexShareResponse:
      allOf:
        - $ref: '#/components/schemas/MoexSecurityResponse'
    OpinionType:
      type: string
      enum:
        - FLAT
        - GENERAL
        - GROWTH
        - REDUCTION
      x-oapi-codegen-extra-tags:
        validate: required,opinionType
    CreateOpinionRequest:
      type: object
      required:
        - date
        - expertId
        - exchange
        - securityId
        - securityType
        - text
        - type
      properties:
        date:
          type: string
          format: date
          x-oapi-codegen-extra-tags:
            validate: required
        exchange:
          $ref: '#/components/schemas/Exchange'
        expertId:
          type: integer
          x-oapi-codegen-extra-tags:
            validate: required
        securityId:
          type: integer
          x-oapi-codegen-extra-tags:
            validate: required
        securityType:
          $ref: '#/components/schemas/SecurityType'
        sourceLink:
          type: string
        targetPrice:
          type: number
          format: double
        text:
          type: string
          x-oapi-codegen-extra-tags:
            validate: required
        type:
          $ref: '#/components/schemas/OpinionType'
    OpinionResponse:
      type: object
      required:
        - id
        - date
        - expertId
        - exchange
        - securityId
        - securityType
        - text
        - type
      properties:
        id:
          type: integer
        date:
          type: string
          format: date
        exchange:
          $ref: '#/components/schemas/Exchange'
        expertId:
          type: integer
        securityId:
          type: integer
        securityType:
          $ref: '#/components/schemas/SecurityType'
        sourceLink:
          type: string
        targetPrice:
          type: number
          format: double
        text:
          type: string
        type:
          $ref: '#/components/schemas/OpinionType'
    PortfolioResponse:
      type: object
      required:
        - id
        - compound
        - name
      properties:
        id:
          type: integer
        compound:
          type: boolean
        name:
          type: string
        userId:
          type: integer
    PortfolioListResponse:
      type: array
      items:
        $ref: '#/components/schemas/PortfolioResponse'
    UpdatePortfolioRequest:
      type: object
      required:
        - id
      properties:
        id:
          type: integer
        name:
          type: string
        compound:
          type: boolean
    CreatePortfolioRequest:
      type: object
      required:
        - name
        - compound
      properties:
        name:
          type: string
        compound:
          type: boolean
    PositionResponse:
      type: object
      required:
        - amount
        - averagePrice
        - currentPrice
        - currentCost
        - securityType
        - shortName
        - ticker
      properties:
        amount:
          type: integer
        averagePrice:
          type: number
          format: double
        comment:
          type: string
        currentPrice:
          type: number
          format: double
        currentCost:
          type: integer
        securityType:
          $ref: '#/components/schemas/SecurityType'
        shortName:
          type: string
        targetPrice:
          type: number
          format: double
        ticker:
          type: string
    DealResponse:
      allOf:
        - $ref: '#/components/schemas/CreateDealRequest'
        - type: object
          properties:
            id:
              type: integer
    TransactionType:
      type: string
      enum:
        - DEPOSIT
        - CASHOUT
    CreateTransactionRequest:
      type: object
      required:
        - amount
        - date
        - portfolioId
        - type
      properties:
        amount:
          type: integer
        date:
          type: string
          format: date-time
        portfolioId:
          type: integer
        type:
          $ref: '#/components/schemas/TransactionType'
    TransactionResponse:
      allOf:
        - $ref: '#/components/schemas/CreateTransactionRequest'
        - type: object
          required:
            - id
          properties:
            id:
              type: integer
    FullPortfolioResponse:
      type: object
      properties:
        bondPositions:
          type: array
          items:
            $ref: '#/components/schemas/PositionResponse'
        cash:
          type: integer
        cashoutsSum:
          type: integer
        compound:
          type: boolean
        deals:
          type: array
          items:
            $ref: '#/components/schemas/DealResponse'
        depositsSum:
          type: integer
        id:
          type: integer
        name:
          type: string
        profitability:
          type: integer
        sharePositions:
          type: array
          items:
            $ref: '#/components/schemas/PositionResponse'
        totalCost:
          type: integer
        transactions:
          type: array
          items:
            $ref: '#/components/schemas/TransactionResponse'
      required:
        - bondPositions
        - cash
        - cashoutsSum
        - compound
        - deals
        - depositsSum
        - id
        - name
        - profitability
        - sharePositions
        - totalCost
        - transactions
    Role:
      type: string
      enum:
        - ADMIN
        - INVESTOR
    RegisterUserRequest:
      type: object
      required:
        - email
        - name
        - password
      properties:
        email:
          type: string
        name:
          type: string
        password:
          type: string
        role:
          $ref: '#/components/schemas/Role'
